---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@36527a2230bed48409ccd595b17f8344efe0acdd # 20261001.1
