---
name: Lint general

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    uses: timmo001/workflows/.github/workflows/lint-general.yml@722ef29d1740604bd16be91fde520339d2cfadbb # master
